### ISSUE TITLE
Permanently Closed tap sites showing up on map

### ISSUE THREAD

**Issue by affabillyty** [phlask/phlask-map#112]
Some businesses on the PHLASK Map have permanently closed and are no longer in business. As a user, I do not want these businesses (or locations) to ever be displayed on the Map as they will never be accessible.

We should ensure that businesses/locations that have been marked "Permanently Closed" on Google no longer are displayed on the PHLASK Map.

look-up boolean permanently_closed

**Comment by nwyin** [comment]
Wanted to resurface this issue and clarify if it should be closed? It seems like a branch has already been merged for it.
