### ISSUE TITLE
User Tutorial

### ISSUE THREAD

**Issue by gcardonag** [phlask/phlask-map#114]
**Is your feature request related to a problem? Please describe.**
As some users have looked at Phlask recently, one thing that has come up is that it isn't clear what the colors on the taps in the map indicate.

**Describe the solution you'd like**
It would be nice to have some kind of tutorial for new users to learn how to engage with our app. It should also have an easy way to opt-out of the tutorial for regular visitors.

**Describe alternatives you've considered**
In the past, we've included hover-text on the legend to show detail around the different tap types. We should probably include this kind of information in the tutorial as well since hover-text likely won't work for mobile users.

**Comment by PeterArriaza** [comment]
Completed with merge of rasha/modal
