### ISSUE TITLE
Food location hours inconsistently disappear

### ISSUE THREAD

**Issue by gcardonag** [phlask/phlask-map#146]
**Describe the bug**
Upon loading the map and reviewing the People’s Emergency Center food location at 3750 Lancaster Ave., the hours do not appear. However, upon clicking another location nearby (for example, Westpark Apartments at 300 N. Busti Street) and then clicking back upon the original location, the hours show up again. It is not clear what is causing this behavior, as no errors are shown in the console.

**To Reproduce**
1. Load the beta map (beta.phlask.me)
2. Switch to food taps
3. Click on the People’s Emergency Center food location at 3750 Lancaster Ave.
4. Hours do not appear

**Expected behavior**
An hours dropdown should appear at the location

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by LizKalter** [comment]
@gcardonag Please see PR #148 for an explanation of the weird behavior with the hours dropdown we were seeing Tuesday.
