### ISSUE TITLE
images in welcome modal not displaying properly

### ISSUE THREAD

**Issue by PeterArriaza** [phlask/phlask-map#147]
The icons in the welcome modal on the last page (legend) are misaligned/incorrect:
- Shared icon should be green
- Recreation showing next to School icon
- Congregation not showing at all

I'd also suggest splitting the legend into two different pages - one for water and one for food.  Currently the legend extends beyond the screen height.  

Additionally, each successive page keeps the focus on the "Next/Close" button.  This should be removed and upon viewing a new page, neither of the buttons at the bottom should be already focused.

**Comment by katjost** [comment]
This issue has been replaced by a new project: [Welcome Modal/Product Tour](https://docs.google.com/document/d/1tvzlZNwQNdwRF6ff4wmnl9a0br3wScvTPH56mjJQpoA/edit?usp=sharing)
