### ISSUE TITLE
Tracking returning visitors

### ISSUE THREAD

**Issue by gcardonag** [phlask/phlask-map#151]
**Is your feature request related to a problem? Please describe.**
As a member of the PHLASK team, I would like to be able to track unique visitors so that I can gauge how much usage the map is getting.

**Describe the solution you'd like**
A dashboard that can be used to present metrics regarding any returning users to the phlask map over the last 30 days.

**Describe alternatives you've considered**
N/A

**Additional context**
We can use our existing Google Analytics account for this, in the `PHLASK-TEST` app.

**Comment by LizKalter** [comment]
Google Analytics uses a cookie to recognize returning visitors. The Audience -> Overview page displays a breakdown of new and return visitors.
