### ISSUE TITLE
Unit Test: Add new tap

### ISSUE THREAD

**Issue by keegan2149** [phlask/phlask-map#159]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
Add test tap.  Move it to production in firebase via GCP client.  Verify name, status (closed/open), click on hours dropdown verify information loads with no errors or NaN entires. Delete via GCP client.

**Additional context**
N/A

**Comment by gcardonag** [comment]
Replacing this ticket with the following ones that break this task out a bit more https://github.com/phlask/phlask-map/issues/467 https://github.com/phlask/phlask-map/issues/468 https://github.com/phlask/phlask-map/issues/469 https://github.com/phlask/phlask-map/issues/470 https://github.com/phlask/phlask-map/issues/471 https://github.com/phlask/phlask-map/issues/472
