### ISSUE TITLE
add AR functionally to highlight close by taps

### ISSUE THREAD

**Issue by mkhsharif** [phlask/phlask-map#16]
This feature is aimed to help users find taps that may be hidden inside buildings or just not in plain sight. The user can point their phone in any direction and taps, within proximity, will display in augmented reality.

**Comment by dibleauzah** [comment]
@gcardonag: Hi! Is this resolved?

**Comment by gcardonag** [comment]
Hi @dibleauzah ! This isn't resolved yet. The technical requirements for this today make it more of a moonshot for now.

**Comment by dibleauzah** [comment]
Not necessary at the moment.
