### ISSUE TITLE
Scrape tree data from OpenTreeMap

### ISSUE THREAD

**Issue by carpetofgreenness** [phlask/phlask-map#167]
**Is your feature request related to a problem? Please describe.**
I want to know where all the edible trees are.

**Describe the solution you'd like**
I would like to see a pin on every edible tree in Philadelphia, specifically Juneberries, Mulberries, and Ginkos. The location data for these trees should be scraped from OpenTreeMap using Python.

**Describe alternatives you've considered**
We considered using the Philadelphia Street Tree Inventory, but that data seemed out of date. We also considered using iNaturalist, but they didn't have a large amount of data.

**Additional context**
Should we retrieve the data by downloading CSV files? Should we use selenium to navigate the web page on OpenTreeMap? We'll need to decide.

**Comment by zeeatwork** [comment]
Link to repo 

https://github.com/phlask/tree_map_data_scraping

**Comment by zeeatwork** [comment]
complete.  See repo above.
