### ISSUE TITLE
Initial Database Cleanup

### ISSUE THREAD

**Issue by gcardonag** [phlask/phlask-map#175]
**Is your feature request related to a problem? Please describe.**
In order to ease onboarding and future development, we would like to deprecate our current Firebase databases and replace them with a standard set of databases to support all of our planned environments.

**Describe the solution you'd like**
- [x] All Firebase databases are deleted, except for the following:
  - phlask-web-map-food-hours
  - phlask-web-map-updated-hours
  - phlask-users
  - phlask-web-map-forage
  - phlask-web-map-geofire
  - phlask-web-map-test-new
  - phlask-web-map-updated-hours
 
- [x] The following new Firebase databases are created:
  - phlask-web-map-test-water-live
  - phlask-web-map-test-water-verify
  - phlask-web-map-test-food-live
  - phlask-web-map-test-food-verify
  - phlask-web-map-beta-water-live
  - phlask-web-map-beta-water-verify
  - phlask-web-map-beta-food-live
  - phlask-web-map-beta-food-verify
  - phlask-web-map-prod-food-live
  - phlask-web-map-prod-food-verify
  - phlask-web-map-prod-water-live
  - phlask-web-map-prod-water-verify

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by zeeatwork** [comment]
I have not deleted phlask-web-map because it is currently the default database.  Let me know if you'd like to assign one of the new databases as the default

**Comment by zeeatwork** [comment]
I also kept 'phlask-web-map-food-updated' because you've listed updated hours twice.  I'm not sure if you meant to list 'updated hours' only or 'updated hours and 'food-updated'

**Comment by zeeatwork** [comment]
complete

**Comment by gcardonag** [comment]
Hey Zenzi, after reviewing in Firebase, it seems we cannot delete the phlask-web-map DB because it is tied to the Firebase project (hence the shared name). We can leave that one as-is but lock down its permissions so that it can't be read/written to.

Regarding the phlask-web-map-food-updated database, we can clean that one up as well since it is no longer referenced in our codebase.  Thanks for checking!
