### ISSUE TITLE
Implement Google address auto-complete in form

### ISSUE THREAD

**Issue by katjost** [phlask/phlask-map#196]
Currently, it is painful to manually enter a full address into the crowdsource form.

Ideally, Google maps would auto-complete the address / show suggested addresses based on what is being inputted.

**Comment by nwyin** [comment]
Working on this and have a version working!

Could use some touch up on stylings + handling edge cases, but works for some common use cases I tested for. If we could some more hands to test inputs and just verify that it works would probably give me more peace of mind.

![image](https://user-images.githubusercontent.com/19523341/133502646-8d345a2d-f387-46b9-a43e-09051ada07d7.png)

tagging @affabillyty to keep him in the loop.

**Comment by nwyin** [comment]
Closing this for now given that crowdsourcing form issue has been closed and PR is merged. Address auto-complete is working, but admittedly it's limited based on Google Map's API.

Future enhancements to this feature should be created in a new issue.
