### ISSUE TITLE
node sass ARM architecture "unsupported runtime error"

### ISSUE THREAD

**Issue by jiajingan** [phlask/phlask-map#198]
Device:
Macbook M1
Node version 16.6.2

There is a problem with node sass not being supported on ARM architecture. https://github.com/sass/node-sass/issues/3033
Tried all the solution from this solutions GitHub post. This might be an ARM with node sass problem. 
The problem won't build correctly, after yarn start. 
"Error: Node Sass does not yet support your current environment: OS X Unsupported architecture (arm64) with Unsupported runtime (93)"
<img width="1097" alt="Screen Shot 2021-08-17 at 7 19 16 PM" src="https://user-images.githubusercontent.com/65265220/129812858-86df4172-34ab-4e11-8f31-6b3dca1209f4.png">

**Comment by nwyin** [comment]
Solved!

new cpu architecture is not supported for our version of node-sass.

using another [sass library](https://www.npmjs.com/package/sass) that has more recent maintainers address the issue.
