### ISSUE TITLE
Write unit tests for our crowdsourcing forms

### ISSUE THREAD

**Issue by gcardonag** [phlask/phlask-map#199]
**Is your feature request related to a problem? Please describe.**
As a PHLASK developer, I would like to ensure changes to the crowdsourcing components do not affect the ability for users to successfully submit taps of any type.

**Describe the solution you'd like**
In order to verify this for all commits in our repository, we would like to add a new test called `crowdsourcing-form.js` under this location: https://github.com/phlask/phlask-map/tree/develop/cypress/integration 

For guidance on how to write the test, see:
- The official guide from Cypress: https://docs.cypress.io/guides/getting-started/writing-your-first-test
- One of our previous tests: https://github.com/phlask/phlask-map/blob/develop/cypress/integration/water-tap-viewing.spec.js

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by mandyshri101** [comment]
Any idea how can I run the cypress run command here ? I am trying to run the existing cypress tests by running cypress run command. It is saying this error: Could not start Xvfb. Install XVFB and run Cypress again

**Comment by gcardonag** [comment]
Replacing this ticket with the following ones that break this task out a bit more #467 #468 #469 #470 #471 #472 
@mandyshri101 feel free to take any of these to continue developing crowdsourcing tests
