### ISSUE TITLE
Just Testing This Issue-Submission Feature

### ISSUE THREAD

**Issue by dibleauzah** [phlask/phlask-map#207]
**Is your feature request related to a problem? Please describe.**
N/A: Just testing the feature.

**Describe the solution you'd like**
N/A: Just testing the feature.

**Describe alternatives you've considered**
N/A: Just testing the feature.

**Additional context**
N/A: Just testing the feature.

**Comment by nwyin** [comment]
@dibleauzah If you feel comfortable, could we close out this issue since it's not tied to any action items? Thanks!

**Comment by dibleauzah** [comment]
Sure! Close it!
