### ISSUE TITLE
Create V.2 Filter

### ISSUE THREAD

**Issue by dibleauzah** [phlask/phlask-map#215]
**Is your feature request related to a problem? Please describe.**
As a PHLASK user, I need to be able to filter the PHLASK map by PHLASK tap attributes.

**Describe the solution you'd like**
- Ability to filter the map according to attributes of the active resource UI.

**Describe alternatives you've considered**
N/A--TBD

**Additional context**:
Already outlined in [FilterDrawer.js](https://github.com/phlask/phlask-map/blob/develop/src/components/FilterDrawer/FilterDrawer.js)
This should be built using the Material-UI Drawer component: https://mui.com/material-ui/react-drawer/
Refer to the PHLASK team library [Figma][(https://www.figma.com/file/l0lBzwPalGUg6JjcOXD2Xs/PHLASK--team-library?type=design&node-id=852%3A40805&t=tIJrPuOTV2hLlaRs-1](https://www.figma.com/file/l0lBzwPalGUg6JjcOXD2Xs/PHLASK--team-library?type=design&node-id=852%3A40805&t=tIJrPuOTV2hLlaRs-1))

**Comment by lmpanke** [comment]
See notes in ticket: Create V.2 Filter #217

**Comment by edlopez000** [comment]
Please note the above comment above refers to the ResourceMenu. This is different component and is not related.

**Comment by edlopez000** [comment]
Additional notes: 
- multi-select of filters should be enabled
- the Apply-button should be white when no filter has been selected and turn blue as soon as a filter selection has been made
- the filter content has to adjust to the resource type according to the graphql database
- the Clear-All-button is supposed to deselect all filter choices but the filter should stay open
- the filter can be closed by either tapping on the background OR sliding the filter modal down

**Comment by edlopez000** [comment]
@caseyvaughn Any updates on this ticket?

**Comment by affabillyty** [comment]
Hey @caseyvaughn , following up here on @edlopez000 's comment - do you need any support for this? Are you still interested in pursuing this ticket? We can certainly loop in @tnguyen21 or @gcardonag if some problem solving would help.

**Comment by gcardonag** [comment]
As an additional (but not required) note, we'd like to have the filter panel pop-in from the right on Desktop

**Comment by hannarosenfeld** [comment]
Hi, I am currently working on this. I created the filter drawer according to the template on figma, but the actual filters are not hooked up yet. I will work on that over the next two weeks.

[link to design template on figma](https://www.figma.com/file/VGGqwl3Eq3GQIAO9I6LoNW/phlask?node-id=3061%3A21240)

**Comment by affabillyty** [comment]
There are buttons on the drawer, and when you click on the buttons the interface is filtering based on that filter.

Cited example with: when filtering for "Open Now" taps, the map displays only the locations that are open based on time

**Comment by freelyPheobe** [comment]
Hey @jordanforbes, is this an active ticket? Is this something that's in progress or not? Are there any impediments or general support needed? We're trying to clean up tickets and updates...

**Comment by jordanforbes** [comment]
@freelyPheobe yes it is, I'm still working on it. The main issue is that the filters weren't included in the redux state, but we discussed that at the meeting last night so hopefully this will be fixed. In addition some css needs to be tweaked.

**Comment by jordanforbes** [comment]
Also it's currently just buttons and not a form. As a result the apply and clear buttons currently do nothing.

**Comment by jordanforbes** [comment]
But the main intended function of filtering places using a redux state change does work.

**Comment by CmonUlot** [comment]
Just updated the Figma link; each Resource's filter is laid out. There are a few changes with the copy.

**Comment by freelyPheobe** [comment]
@jordanforbes, is there any code you can share with a new developer working on this ticket?
