### ISSUE TITLE
Create V.2 ClosestTap

### ISSUE THREAD

**Issue by dibleauzah** [phlask/phlask-map#216]
**Is your feature request related to a problem? Please describe.**
When I click on the Phlask button in the Toolbar, I need the map to center on the closest location and have the half-modal of the closest location to pop up

**Describe the solution you'd like**
- Half modal should populate with the proper data (closest location to user)
- Be responsive to mobile view

**Describe alternatives you've considered**
XX

**Additional context**
[Figma file](https://www.figma.com/file/VGGqwl3Eq3GQIAO9I6LoNW/phlask?node-id=2490%3A10454)
Look for the "Home" design, the ClosestTap button is the button in the footer labelled "PHLASK"

**Comment by edlopez000** [comment]
Hi @jvstn, are you still working on this ticket?

**Comment by freelyPheobe** [comment]
Hey @hhoude36 , we haven't seen you in a while. Did you need support with this ticket?

**Comment by tomporvaz** [comment]
There is a new figma mockup of this behavior here: https://www.figma.com/proto/VGGqwl3Eq3GQIAO9I6LoNW/PHLASK?type=design&node-id=6451-77552&t=TCx5FWdmeMtFAYql-0&scaling=min-zoom&page-id=4510%3A29556&starting-point-node-id=6451%3A77748&show-proto-sidebar=1

**Comment by tomporvaz** [comment]
Joe needs to talk with designer about button design.

**Comment by affabillyty** [comment]
Hey @JosephAni , looking at the notes above, Tom mentioned you needed to consult with the Design Circle for a button design, but you have also subsequently removed yourself from this ticket. Will you be working on this one anymore, or do we need to identify a new contributor to advance this one?

**Comment by freelyPheobe** [comment]
Ticket #385 is the newer version.
