### ISSUE TITLE
Create V.2 ResourceMenu

### ISSUE THREAD

**Issue by dibleauzah** [phlask/phlask-map#217]
**Is your feature request related to a problem? Please describe.**
As a PHLASK user, I need the ability to filter the PHLASK resources by different PHLASK-tap attributes in order to find the resources I am looking for.

**Describe the solution you'd like**
- A filter that enables the user to filter the map based on different attributes.
- Needs to change the Phlask button based on selected resource

**Describe alternatives you've considered**
N/A

**Additional context**
We need the filter to work on all these different interfaces--water, foraging, bathroom, and food--and we need it to display the attributes that relay the current interface.
[Figma Link](https://www.figma.com/file/VGGqwl3Eq3GQIAO9I6LoNW/phlask?node-id=3061%3A21653)
>> Please reference the prototype page, and see "Home + Water Filter," the other, "Home + Water Filter (Selected)."

**Comment by affabillyty** [comment]
Note to self: design this ticket to consolidate ALL filters for the different Resource Interfaces

**Comment by lisapancakes** [comment]
Small UI-design changes might be made to the current prototype. The structure stays the same. 
Additional notes: 
- multi-select of filters should be enabled
- the Apply-button should be white when no filter has been selected and turn blue as soon as a filter selection has been made
- the filter content has to adjust to the resource type according to the graphql database
- the Clear-All-button is supposed to deselect all filter choices but the filter should stay open
- the filter can be closed by either tapping on the background OR sliding the filter modal down

**Comment by edlopez000** [comment]
@lisapancakes @CmonUlot When using the app, do we want the map to center on the user's location whenever they switch resource types? That's the way the app currently works and it can be a disorienting experience.

Update: Heard back from the Design team, the map should stay where it is when switching resources.
