### ISSUE TITLE
Create V.2 Images

### ISSUE THREAD

**Issue by dibleauzah** [phlask/phlask-map#220]
Is your feature request related to a problem? Please describe.
XX

Describe the solution you'd like
XX

Describe alternatives you've considered
XX

Additional context
XX

**Comment by affabillyty** [comment]
Note to self: is a folder for iconography; maybe don't need it anymore. Have someone look through this and see if/how it will be needed

**Comment by edlopez000** [comment]
Feels a little redundant as a were shifting towards SVGs and other types of assets per #261.
