### ISSUE TITLE
Create V.2 Legend 

### ISSUE THREAD

**Issue by dibleauzah** [phlask/phlask-map#221]
Is your feature request related to a problem? Please describe.
As a user I would wish for a legend to show me what the different PHLASK-tap markers mean.

Describe the solution you'd like
A map legend for the desktop version of the app to help show what the different PHLASK-tap markers mean.

Describe alternatives you've considered
N/A

Additional context
Primary focus on desktop-version, not mobile.

**Comment by affabillyty** [comment]
Note to self: referred to the old legend for desktop version when there was only a water map; referred to the 4 different water tap types

**Comment by dibleauzah** [comment]
@affabillyty: So, does this mean we should close this ticket?

**Comment by lisapancakes** [comment]
Legend might not be necessary, because we probably won't use the different colored water tap icons anymore. There will only be 4 types of markers for water (blue), food (orange), toilets (grey), and foraging (green). Ideally, the icons should speak for themselves.

**Comment by edlopez000** [comment]
Per conversation above, marking this closed.

**Comment by edlopez000** [comment]
Closing with the right tag.
