### ISSUE TITLE
Replace `node-sass` dependency with `sass`

### ISSUE THREAD

**Issue by nwyin** [phlask/phlask-map#223]
**Describe the bug**
`node-sass` is leading to an install error due to [being depreciated](https://www.npmjs.com/package/node-sass). A replacement is `sass`

We could also look at other libraries

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by affabillyty** [comment]
When this is resolved, tag all contributors to make the update and reinstall on their environment

**Comment by edlopez000** [comment]
Issue was resolved in Pull Request #252
