### ISSUE TITLE
Create V.2 MapMarkers

### ISSUE THREAD

**Issue by dibleauzah** [phlask/phlask-map#224]
Is your feature request related to a problem? Please describe.
As we prepare to deploy PHLASK 2.0, we would like to update our markers to use the new designs prepared by our design team.

Describe the solution you'd like
We would like the map markers displayed for all of our resources to match the designs listed here: https://www.figma.com/file/VGGqwl3Eq3GQIAO9I6LoNW/PHLASK?node-id=4550%3A31103&t=rE3z6jHsaxqt5JTG-1 

Describe alternatives you've considered
n/a

Additional context
n/a

**Comment by affabillyty** [comment]
Note to self: displaying the PHLASK Tap pins on the map

**Comment by lisapancakes** [comment]
The map pins have not been designed yet. If you want to start on this, I suggest removing the differently colored phlask-icons for water taps and implementing the following pins only: 
- water (drop icon), color: blue
- food, color: orange
- toilets, color: grey
- foraging, color: green

**Comment by gcardonag** [comment]
As a part of this, we would like to also be able to render Foraging and Bathroom-type data on the map. We'll need to add new IndieXMarker-type and MapMarkersX-type Components to handle those two cases. We can follow the similarly-named components in the project as a starting point and add references to the MapMarkersX-type components to the MapMarkersMapper component.

**Comment by tomporvaz** [comment]
Daniel Cha is picking this ticket up but does not have a github account in project yet.

**Comment by tomporvaz** [comment]
SVGs of the pins are in this [google drive folder](https://drive.google.com/drive/folders/1mOa8EN8VZIZaigvH0IIGZM-MixVaWA2g?usp=drive_link), and the filenames begin with pin.

**Comment by tomporvaz** [comment]
@a-maci29 to help @DancyyDev navigate code

**Comment by DancyyDev** [comment]
For the food icons, there are many different icons that pop up, are we consolidating all the food icons into one icon? @tomporvaz @freelyPheobe

**Comment by tomporvaz** [comment]
Needs help from design.

**Comment by tomporvaz** [comment]
@gcardonag to add bathroom and foraging data to test dbs for testing purposes.

**Comment by freelyPheobe** [comment]
So far, everything is running smoothly. Image being replaced for foraging and database needs to still be connected.

**Comment by tomporvaz** [comment]
working on adding the active pin as well.

**Comment by tomporvaz** [comment]
Half complete.  Foraging and Bathroom pins are not added yet, and these types cannot be verified without data. This work can continue when #399 is complete.

**Comment by tomporvaz** [comment]
Still blocked, but a big PR related to the Data schema coming soon may resolve this issue, or at least unblock it.

**Comment by gcardonag** [comment]
Hey @DancyyDev ! We're just digging through some of our v2 ticket backlog and saw this. Is there any help/support you'd like with the work you've been doing here?

**Comment by gcardonag** [comment]
@DancyyDev disregard this! We'll close this in favor of https://github.com/phlask/phlask-map/issues/386 (but offer is still open to support!)
