### ISSUE TITLE
Create V.2 MapPage

### ISSUE THREAD

**Issue by dibleauzah** [phlask/phlask-map#225]
Is your feature request related to a problem? Please describe.
XX

Describe the solution you'd like
XX

Describe alternatives you've considered
XX

Additional context
XX

**Comment by affabillyty** [comment]
Note to self: this is a wrapper around the Google Maps component; could be refactored in the future

#227 related ticket.

**Comment by gcardonag** [comment]
This can be pulled out of scope for V2 since there are no wrapper-related changes in-scope.
