### ISSUE TITLE
Create V.2 Pages

### ISSUE THREAD

**Issue by dibleauzah** [phlask/phlask-map#226]
Is your feature request related to a problem? Please describe.
As a User, I need to view the project information on different webpages - on both desktop and mobile versions.

https://www.figma.com/file/VGGqwl3Eq3GQIAO9I6LoNW/PHLASK?type=design&node-id=4510-29556&mode=design&t=YG7IKEW4q6elN4Mn-0 

Describe the solution you'd like
- Mission
- Project
- Share
- Contribute

Describe alternatives you've considered
XX

Additional context
[Website Content](https://docs.google.com/document/d/1I8TpkpNTegCukErrbYvzqTYbbPeMlPtFl9jAMkbsQOE/edit?usp=sharing)

**Comment by affabillyty** [comment]
Note to self: this is the content pages

**Comment by lisapancakes** [comment]
The design of the content pages has not been updated yet. The pages can stay as they are until they have been designed. Content can already be adjusted by @affabillyty if necessary. Otherwise, I don't think there is much to do here.
