### ISSUE TITLE
Create V.2 ReactGoogleMaps

### ISSUE THREAD

**Issue by dibleauzah** [phlask/phlask-map#227]
**Is your feature request related to a problem? Please describe.**
As a developer, I need to use Google Maps as the base for the features of the PHLASK Map

**Describe the solution you'd like**
XX

**Describe alternatives you've considered**
XX

**Additional context**
XX

**Comment by dibleauzah** [comment]
@affabillyty: Please see relevant Slack-DM note.

**Comment by dibleauzah** [comment]
Note to self: follow-up with one of the dev-circle people for guidance.

**Comment by gcardonag** [comment]
Since there isn't anything to change with our use of Google Maps, we can close this ticket
