### ISSUE TITLE
Create V.2 SearchBar Mobile 

### ISSUE THREAD

**Issue by dibleauzah** [phlask/phlask-map#228]
Is your feature request related to a problem? Please describe.
As a user, 
I want to search for resources, landmarks, or addresses 
in order to find the best resource near me/around a certain location. 

Describe the solution you'd like
- A search bar with auto-fill addresses.
- Searchable by landmarks (nice to have)
- Searchable by Tap Name
- Searchable by resource type (water, food, toilets, etc. with synonyms) (nice to have)

Describe alternatives you've considered
XX

Additional context
[Figma Page](https://www.figma.com/file/VGGqwl3Eq3GQIAO9I6LoNW/PHLASK?type=design&node-id=3427-32115&mode=design&t=AXQfJKURL6T47UEH-4)
See "Search Open" mock-up

Functionality: User clicks on the search icon in the header > search bar appears and field is selected so that users can directly start typing > search gets confirmed by hitting enter OR search bar gets closed by clicking on the closing icon (x)

**Comment by affabillyty** [comment]
Update from Lisa: The closing icon "x" will get a different design, so stay tuned for that update

**Comment by edlopez000** [comment]
Hi @rh9891, we're doing a quick inventory of issue statuses and wanted to see if you had any updates?

**Comment by gcardonag** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create V2 SearchBar](https://trello.com/c/4ydcaDfX/1-create-v2-searchbar)

**Comment by freelyPheobe** [comment]
Hey @RNR1, we see you're assigned to this. Is this something you're actively working on?

**Comment by freelyPheobe** [comment]
Hey @chethtrayen, we haven't seen you in a while. Is there support needed on this ticket?

**Comment by tomporvaz** [comment]
The search bar is currently not working on Phlask mobile. We'd like to make the search appear when the search button is clicked.  An updated design is available here: https://www.figma.com/file/VGGqwl3Eq3GQIAO9I6LoNW/PHLASK?type=design&node-id=8036-117041&mode=design.
Pull request #325 made progress on this ticket, but still contained bugs.

**Comment by tomporvaz** [comment]
Completed in PR #389

**Comment by lxh5395** [comment]
Desktop looks good.

On mobile, I need to double check with Marine to make sure, but I believe that a user should have the ability to deselect the text box, like on desktop, by either pressing enter, selecting one of the search results, or tapping on the map (either pin or background). Deselecting the field would keep the search bar present with any current inputs, but remove the dark overlay over the map. If deselected it should also help with the keyboard remaining open as a user tries to scroll around. 

Bit nitpicky, but I seem to get some strange behavior on pressing enter on both mobile and desktop that doesn't seem to have any rhyme or reason for cause. On pressing enter sometimes the popup with result remains opens and sometimes it closes.

**Comment by tomporvaz** [comment]
@CmonUlot Please take a look at the search bar functionality and provide feedback about the intended behavior as noted in @lxh5395 review above.

**Comment by tomporvaz** [comment]
Work to be continued in issue #410.
