### ISSUE TITLE
Create V.2 SelectedTap (Half-modal)

### ISSUE THREAD

**Issue by dibleauzah** [phlask/phlask-map#229]
Is your feature request related to a problem? Please describe.
When I click on a PHLASK tap, I need the half-modal of the closest location to pop up.

Describe the solution you'd like
- Half modal should populate with the proper data of the selected tap

Describe alternatives you've considered
- Consider the built-in [Drawer component](https://mui.com/material-ui/react-drawer/) in MUI

Additional context:
[Figma file](https://www.figma.com/file/VGGqwl3Eq3GQIAO9I6LoNW/phlask?node-id=3427%3A30146)
Look for "Half Modal Open" design

## **This issue is linked to issue #250**.

**Comment by affabillyty** [comment]
Update from Lisa: the 'structure' of the half modal is okay, but there may be some small design refinements (tweaks)

**Comment by gcardonag** [comment]
Hey @yingmo55 , this area of the code helps is what builds out the Half and Full Modals for a selected tap: https://github.com/phlask/phlask-map/blob/develop/src/components/SelectedTap/SelectedTap.js#L262-L447

Its a bit of a heavy component that currently renders each part differently depending on if we are using a mobile version of the site, hence the `isMobile` checks throughout this code. Feel free to reach out to me over Slack or this Issue to get more context around how to work on this component! I'm thinking maybe one thing we could do to make things easier is to just use one top-level `isMobile` to break out how the component is built. We can leave the old logic as-is for now under the non-mobile path and use this Issue's work under the mobile path.
