### ISSUE TITLE
Create V.2 SelectedTap (Full-modal)

### ISSUE THREAD

**Issue by edlopez000** [phlask/phlask-map#250]
Is your feature request related to a problem? Please describe.
When the half-modal is open, I need the half-modal to open to the full modal.

Describe the solution you'd like
- Full modal should populate with the proper data from the selected tap; additional data needs to render.
- Note: Full-modal is full screen, additional modal menu buttons across the top

Describe alternatives you've considered
- Consider the built-in [Drawer component](https://mui.com/material-ui/react-drawer/) in MUI

Additional context:
[Figma file](https://www.figma.com/file/VGGqwl3Eq3GQIAO9I6LoNW/phlask?node-id=3061%3A23217)
Look for "Home with Full Modal" design

## **This issue is linked to issue #229**.

**Comment by edlopez000** [comment]
@lisapancakes @CmonUlot The pull bar does not appear on the full-modal design? Is this intentional? Do we want users to be able to go from full-modal to half-modal?

**Comment by lisapancakes** [comment]
@edlopez000 you can reference Google Maps. The half modal goes to full modal by dragging the pull bar up and goes back to half modal when the user taps on the arrow down.
