### ISSUE TITLE
Update Assets to new designs (V2)

### ISSUE THREAD

**Issue by yingmo55** [phlask/phlask-map#261]
**Is your feature request related to a problem? Please describe.**
Right now, the assets in the develop branch are not up-to-date with the new designs in the figma files. It may be better to update the files in `src/components/images`  and `src/components/icons` to the new design and standardize the assets to `.svg` files as well.

**Describe the solution you'd like**
- [ ] update the files in `src/components/images`  and `src/components/icons` 
- [ ] update the file linked in the components

**Describe alternatives you've considered**
N/A

**Additional context**
https://www.figma.com/file/VGGqwl3Eq3GQIAO9I6LoNW/phlask?node-id=4552%3A30849

**Comment by tomporvaz** [comment]
Hi @CmonUlot, this ticket is asking for new assets from figma. Do we still need to update these, and if so, where can we get the most up to date assets?

**Comment by tomporvaz** [comment]
Need to identify the correct assets in Figma.

**Comment by tomporvaz** [comment]
@CmonUlot is working on updating all assets in figma for consistency, and will place all assets (icons and illustrations_ in google drive when done. Stay tuned!

**Comment by gcardonag** [comment]
Closing this as it is already done ✅
