### ISSUE TITLE
Include additional fields in the AddBathroom portion of the AddResourceModal component

### ISSUE THREAD

**Issue by gcardonag** [phlask/phlask-map#262]
**Is your feature request related to a problem? Please describe.**
As a user attempting to submit data to Phlask, I would like to include additional detail when submitting Bathroom-type data. I would like to include the following details:
- Is it accessible? (`handicap` field in our DB)
  - Checkbox Field
- Is ID required for access? (`id_required` field in our DB)
  - Checkbox Field
- Changing table (new `changing_table` field in our DB)
  - Checkbox Field
- Gender neutral (new `gender_neutral` field in our DB)
  - Checkbox Field
- Family bathroom (new `family_bathroom` field in our DB)
  - Checkbox Field
- Single Occupancy (new `single_occupancy` field in our DB)
  - Checkbox Field

**Describe the solution you'd like**

The fields described above should be added to the AddBathroom portion of the AddResourceModal component. No changes to the database are needed, as the new fields should work properly for submission purposes.

**Describe alternatives you've considered**

N/A

**Additional context**

For reference, this came from a request on Slack: https://codeforphilly.slack.com/archives/C03F02LUDJQ/p1656171701447759

**Comment by CmonUlot** [comment]
Please also add "Single Occupancy"
