### ISSUE TITLE
Update the full modal view of a given tap to take up the full screen height

### ISSUE THREAD

**Issue by gcardonag** [phlask/phlask-map#286]
**Is your feature request related to a problem? Please describe.**
This is related to beta site feedback indicating our full modal view does not currently align to our prototype vision for V2 of the site.

**Describe the solution you'd like**
When the tap modal view is expanded to the detailed view, the detailed view should take up the entire page height.

This can be done by updating the new "SelectedTapMobile" component and style: https://github.com/phlask/phlask-map/tree/develop/src/components/SelectedTapMobile

For an example, see the image below:
![image](https://user-images.githubusercontent.com/2278918/199359956-5cac1c5d-3886-4ead-858c-c02c18a47fe1.png)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by freelyPheobe** [comment]
Hey @Natalie-Ann , we haven't seen you in a while. Just checking in if you are still working on this ticket?
