### ISSUE TITLE
Add Acknowledgements Section to the Contribute page component

### ISSUE THREAD

**Issue by gcardonag** [phlask/phlask-map#294]
**Is your feature request related to a problem? Please describe.**
We would like to have an Acknowledgements section available in our Contribute page, such that whenever the page is loaded, a dynamic list of contributors is generated via a reference to our `phlask-contributors` Firebase database. This should be presented as (relative to firebase fields):
```
id
First_Name Last_Name
Circle Names (the ones set to true)
"Convener" (only displayed if the Convener property is true)
Status
```

Only the users with a status set to "Active" or "Engaged" in Firebase should be displayed.

As a secondary addition to this request, we would like to present the list of contributors as a group of panels, displaying each contributor's photo, name, and a few of their attributes.

**Describe the solution you'd like**
For a reference to how this should appear when loading the Contribute page, see here: https://www.figma.com/file/VGGqwl3Eq3GQIAO9I6LoNW/PHLASK?node-id=6144%3A69092&t=WF6RgDjl4eOe3RI1-4 

NOTE: This story should focus on the text content on the preview. For the sake of simplicity, we do not need to enable a tab-like view yet. Instead we should follow the approach that is currently implemented for our subpages:
- Add an Acknowledgements component under `src/components/Pages/`. Use the other pages in this folder for a reference on how to present the content. The goal for this issue is to get the content presented in a readable format. We should not focus on styling yet.
- Add a Route to path "/acknowledgements" pointed to an Acknowledgements component
- Add a an element in `src/components/SideBar/SideBar.js` to allow directing to the acknowledgements path, reuse the other `SidebarLink`-type elements in that component to build it.

**Describe alternatives you've considered**
n/a

**Additional context**
A new firebase connection will need to be created for this component.

**Comment by freelyPheobe** [comment]
@vivek92-tech Just wanted to confirm you're still actively engaging this task. If you need any support please let us know as we can find additional support.

**Comment by gcardonag** [comment]
@vivek92-tech - For reference, I've updated this issue with some more detail that should help guide the implementation from a React perspective.

**Comment by vivek92-tech** [comment]
Hi @gcardonag @freelyPheobe, sorry I was busy during the last few weeks with work and the Holi festival. I have set up the dev environment and will start working on this issue.

**Comment by gcardonag** [comment]
@vivek92-tech - For a reference on how the data structure looks for the phlask-contributors Firebase DB, use this link: https://phlask-contributors.firebaseio.com/.json

**Comment by freelyPheobe** [comment]
@vivek92-tech Hey! How are things going here? We've missed you at hack night these past few weeks and just wanted to check-in. Are there any impediments or general support needed?

**Comment by dibleauzah** [comment]
Hi, folks.

Just a quick fyi: as I promised earlier, I have added myself to this ticket. @vivek92-tech & @gcardonag: I hope that's ok? As in, for two people to be working on it. I can/will follow your lead, @vivek92-tech.

Thanks,
Seif.

**Comment by dibleauzah** [comment]
Update, June 13, 2023:

I just added some code and text updates to the "Contribute" page. Specifically:

--> 1)--I divided the intro paragraph for easier readability; and
--> 2)--I added a new page section: the first part of the contributors' recognition list, i.e., the four circles.

I believe these changes have to be approved by you, @gcardonag? Thanks.

**Comment by dibleauzah** [comment]
Update: as of today--Oct 6, 2023, I have completed the first two tasks of the ticket; i.e.:
>> 1) Add an Acknowledgements component under src/components/Pages/. Use the other pages in this folder for a reference on how to present the content. The goal for this issue is to get the content presented in a readable format. We should not focus on styling yet.
>> 2) Add a Route to path "/acknowledgements" pointed to an Acknowledgements component

**Comment by tomporvaz** [comment]
Closing this issue with PR #354 in favor of issue #355
