### ISSUE TITLE
Create V.2 Toolbar (Desktop)

### ISSUE THREAD

**Issue by gcardonag** [phlask/phlask-map#299]
**Is your feature request related to a problem? Please describe.**
As a part of the effort to deploy PHLASK 2.0, we would like the Toolbar component in the src/components/Toolbar folder to match the design in the Desktop design shared here: https://www.figma.com/file/VGGqwl3Eq3GQIAO9I6LoNW/PHLASK?node-id=6451%3A76312&t=xE1rkr657wCNubGL-4

**Describe the solution you'd like**
A user accessing PHLASK in a Desktop view experiences a design matching the one proposed for PHLASK 2.0. This issue is focused on the Toolbar shown in the bottom-left of the linked Figma design.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by freelyPheobe** [comment]
Hey @gcardonag! Is there a developer assigned to this ticket?

**Comment by freelyPheobe** [comment]
Hey @gcardonag & @RNR1 , we've just assigned this ticket to Joseph. If either of you have any guidance or information for Joseph about this ticket please let him know. Thanks!

**Comment by JosephAni** [comment]
@gcardonag I have the icons in position. Please take a look at my recent push.

**Comment by freelyPheobe** [comment]
Hey @JosephAni and @gcardonag , was the push successful?

**Comment by JosephAni** [comment]
Yes it was successful!

**Comment by JosephAni** [comment]
Tool bar icons improving desktop view experiences a design matching the one proposed for PHLASK 2.0.
![Tool bar](https://github.com/phlask/phlask-map/assets/63737588/d91dc633-597a-43ec-8b36-b3dea6b1a660)
