### ISSUE TITLE
Create legend component

### ISSUE THREAD

**Issue by gcardonag** [phlask/phlask-map#30]
This should be a legend component that presents a mapping from tap types to what they represent. Those can be found here: https://github.com/phlask/phlask-map/blob/master/public/js/phlaskData.js

It should be placed above the map and be an expandable space to allow for easy access on mobile.

**Comment by gcardonag** [comment]
This can probably be replaced with the Toolbar filter but something to discuss later is if this could be part of a short-term modal that pops up when users access the site to quickly give an idea of what the tap-types are.

**Comment by nwyin** [comment]
Hi @gcardonag @PeterArriaza,

Just wanted to know where this issue is currently standing. Is there anything I could do to help with moving this issue forward?
