### ISSUE TITLE
Create V.2 Head+SideBar (Desktop)

### ISSUE THREAD

**Issue by gcardonag** [phlask/phlask-map#301]
**Is your feature request related to a problem? Please describe.**
As a part of the effort to deploy PHLASK 2.0, we would like the Head and Sidebar components in the src/components/Head and src/components/Sidebar folders to match the design in the Desktop design shared here: https://www.figma.com/file/VGGqwl3Eq3GQIAO9I6LoNW/PHLASK?node-id=6451%3A76555&t=xE1rkr657wCNubGL-4

**Describe the solution you'd like**
A user accessing PHLASK in a Desktop view experiences a design matching the one proposed for PHLASK 2.0. This issue is focused on the element shown in the top-left of the linked Figma design. For the expanded view of the sidebar, see the view here: https://www.figma.com/file/VGGqwl3Eq3GQIAO9I6LoNW/PHLASK?node-id=6451%3A77675&t=xE1rkr657wCNubGL-4

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by gcardonag** [comment]
As we chatted about on standup, I'll add the expanded sub-page views for Desktop as a part of this Issue since we didn't have one that captured that portion of the site. For reference, here is the Figma view for how those expanded pages should look: https://www.figma.com/file/VGGqwl3Eq3GQIAO9I6LoNW/PHLASK?node-id=6451-77798&t=okusOMn9SsADSH1X-4

**Comment by freelyPheobe** [comment]
Hey @oxfordblucher, how's it going? Just wanted to check-in if there are any updates with this ticket and/or any obstacles?

**Comment by oxfordblucher** [comment]
Hi, sorry for the radio silence. Got a little busy with work and kinda left this on the backburner. Should have a PR by next week though!

**Comment by oxfordblucher** [comment]
So I was able to get the mobile/desktop views working but I had a question as to how to approach the expanding menu. It's 2-step expansion, clicking on the button first opens up the list, and then clicking on one of the tabs, expands it further. Should I be nesting Poppers here or is there a simpler approach?

**Comment by freelyPheobe** [comment]
Hey @gcardonag, has this been successfully merged?

**Comment by gcardonag** [comment]
> Hey @gcardonag, has this been successfully merged?

Not yet, I'm giving this issue's pull request a look 👀

**Comment by tomporvaz** [comment]
Closed by pull request #313
