### ISSUE TITLE
Create V.2 SearchBar (Desktop)

### ISSUE THREAD

**Issue by gcardonag** [phlask/phlask-map#302]
**Is your feature request related to a problem? Please describe.**
As a part of the effort to deploy PHLASK 2.0, we would like the SearchBar component in the src/components/SearchBar folder to match the design in the Desktop design shared here: https://www.figma.com/file/VGGqwl3Eq3GQIAO9I6LoNW/PHLASK?node-id=6451%3A77014&t=xE1rkr657wCNubGL-4

**Describe the solution you'd like**
A user accessing PHLASK in a Desktop view experiences a design matching the one proposed for PHLASK 2.0. This issue is focused on the Searchbar shown in the bottom-left of the linked Figma design.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Erw1nn** [comment]
I asked if I could work on this at Hack Night and they gave me the green light, so I assigned it to myself 🙂

**Comment by gcardonag** [comment]
Closing this one as complete 🎉
