### ISSUE TITLE
Create V.2 ResourceMenu (Desktop)

### ISSUE THREAD

**Issue by gcardonag** [phlask/phlask-map#303]
**Is your feature request related to a problem? Please describe.**
As a part of the effort to deploy PHLASK 2.0, we would like the ResourceMenu component in the src/components/ResourceMenu folder to match the design in the Desktop design shared here: https://www.figma.com/file/VGGqwl3Eq3GQIAO9I6LoNW/PHLASK?node-id=6451%3A77528&t=xE1rkr657wCNubGL-4

**Describe the solution you'd like**
A user accessing PHLASK in a Desktop view experiences a design matching the one proposed for PHLASK 2.0. This issue is focused on the menu shown in the bottom-left of the linked Figma design.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by freelyPheobe** [comment]
Hey  @ncatin, has this ticket been completed?

**Comment by gcardonag** [comment]
Closing this as it has been completed
