### ISSUE TITLE
Create V.2 FilterDrawer (Desktop)

### ISSUE THREAD

**Issue by gcardonag** [phlask/phlask-map#304]
**Is your feature request related to a problem? Please describe.**
As a part of the effort to deploy PHLASK 2.0, we would like the FilterDrawer component in the src/components/FilterDrawer folder to match the design in the Desktop design shared here: https://www.figma.com/proto/VGGqwl3Eq3GQIAO9I6LoNW/PHLASK?page-id=4510%3A29556&type=design&node-id=8105-140052&viewport=889%2C-851%2C0.09&scaling=scale-down&starting-point-node-id=8105%3A139899&show-proto-sidebar=1&mode=design 

**Describe the solution you'd like**
A user accessing PHLASK in a Desktop view experiences a design matching the one proposed for PHLASK 2.0. This issue is focused on the Filter Drawer shown in the bottom-left of the linked Figma design.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by jordanforbes** [comment]
I've actually been working on this. Right now we don't have the full list of suggested filters implemented in the redux store so I only have the three that work on the filter at the moment. It does work, however.

**Comment by gcardonag** [comment]
For anyone working on this, I updated the drawer visual target to a newer version with a prototype that covers filters for each resource type.
