### ISSUE TITLE
Update the wording upon acknowledgement of a contribution

### ISSUE THREAD

**Issue by gcardonag** [phlask/phlask-map#324]
**Is your feature request related to a problem? Please describe.**
In order to better communicate to users that their contributions will undergo a manual review and will not immediately be added, we would like to change the text that appears when a contribution is submitted to the following:
```
Thanks for sharing! Your submission is under review.
```

This would require an update to the ShareSocials component.

**Describe the solution you'd like**
We do not currently have a prototype visual for this, but the text after a submission is entered should match the text shared above.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by affabillyty** [comment]
Hey @freelyPheobe , I'm guessing you're not still moving on this one - should we see if someone else wants to pick it up? It's tagged as a good first issue.

**Comment by tomporvaz** [comment]
Closing as no longer necessary because the Phlask 2.0 has confirmation modal that displays this information after submitting a new site.
