### ISSUE TITLE
Resource Type

### ISSUE THREAD

**Issue by freelyPheobe** [phlask/phlask-map#349]
**Describe the bug**
 When I click on the _resources_ modal the following message reads "Add a site" but it should read "Resource Type."

Refer to ticket #345 for additional context

 Current state
![image](https://github.com/phlask/phlask-map/assets/104399179/df0a7e0d-fa2a-4e10-a92d-5a76cf0159a9)
**To Reproduce**

**Expected behavior**
Updated state
![image](https://github.com/phlask/phlask-map/assets/104399179/01499f23-6f49-4491-9b16-48ff79098380)

**Comment by JosephAni** [comment]
Resources modal now reads the following message "Resource Type."
![Resources modal](https://github.com/phlask/phlask-map/assets/63737588/e557eb92-98bb-48e5-9bf2-1c04f639ea3d)

**Comment by lxh5395** [comment]
**Design check:**
 Looks good!

**Comment by affabillyty** [comment]
Re-opened; merge request not yet completed

**Comment by tomporvaz** [comment]
Despite the PR #351 never having been merged, it appears that the Beta site now matches the figma design which say "Show Resource Type" 
https://www.figma.com/file/VGGqwl3Eq3GQIAO9I6LoNW/PHLASK?type=design&node-id=8303-153128&mode=design&t=sIaTQXTFkp2mkx2a-0
![Show_Resource_Type](https://github.com/phlask/phlask-map/assets/45155555/857fbff2-c781-4db9-9c10-1b8eb2e1dd9c)
