### ISSUE TITLE
Recreate Phlask mission page

### ISSUE THREAD

**Issue by gcardonag** [phlask/phlask-map#36]
Our Phlask mission page needs to be recreated using the content from: https://phlask.me/ecosystem/

Concerns:
-Would like to be able to maintain consistent styling vs what is on the current site

**Comment by nwyin** [comment]
Just leaving a comment to resurface this ticket. I'm happy to take this on! Just can't find the old content that needs to be migrated. Feel free to @me if the content becomes available somewhere.
