### ISSUE TITLE
Foraging and Near Me crashes

### ISSUE THREAD

**Issue by freelyPheobe** [phlask/phlask-map#362]
**Describe the bug**
If I change resource type to foraging, and click the near me button, the app crashes

1. Go to Resources
2. Click on Foraging
3. Click on Near Me
4. See error, Behold the crashing in all its glory "White Screen"

**Expected behavior**
 Just as after Water or Food resource type is selected and then the "Near Me" button is clicked and updated to your location. The same should happen for Foraging.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 N/A

**Smartphone (please complete the following information):**
 N/A
**Additional context**
N/A

**Comment by tomporvaz** [comment]
Should be fixed when issue #399  is complete.

**Comment by vontell** [comment]
This will be part of my new data schema PR #433

**Comment by tomporvaz** [comment]
@vontell is making a big PR related to the new data schema that will address this issue soon.

**Comment by tomporvaz** [comment]
This appears to be fixed.
