### ISSUE TITLE
An X that closes the filter modal

### ISSUE THREAD

**Issue by tomporvaz** [phlask/phlask-map#363]
**Is your feature request related to a problem? Please describe.**
The filter menu should have an X in the top right to close the modal.
![Screenshot from 2023-12-28 12-21-24](https://github.com/phlask/phlask-map/assets/45155555/367014de-957e-4c7f-9cd7-1df6bd2f4a0a)
https://www.figma.com/file/VGGqwl3Eq3GQIAO9I6LoNW/PHLASK?type=design&node-id=8303-156456&mode=design&t=vVRkRN4MSA1SQjJY-4

**Describe the solution you'd like**
an X that closes the filter modal

**Describe alternatives you've considered**
n/a

**Additional context**
Issue #215 and #304

**Comment by tomporvaz** [comment]
Should be assigned to Alex.

**Comment by affabillyty** [comment]
Hey @tomporvaz and @JosephAni , was this the ticket that Joseph briefly was helping newcomer Andrew with? If so, I think this needs to move back to "Ready" and be reassigned, unless Joe is planning to pick it up himself and continue with it

**Comment by JosephAni** [comment]
A close icon button was added to the filter. Pls review. 

![Image](https://github.com/phlask/phlask-map/assets/63737588/19b7a06b-bde0-4593-bfab-7627e010de1f)

**Comment by tomporvaz** [comment]
PR #397

**Comment by tomporvaz** [comment]
@RNR1 I don't see the close button on the filter in Beta.  Is there another step, or do you think other code might have overwritten Joe's changes?
