### ISSUE TITLE
"Join the team" updated design for Desktop

### ISSUE THREAD

**Issue by freelyPheobe** [phlask/phlask-map#365]
**Is your feature request related to a problem? Please describe.**
This request a not a problem but an updated design.

**Describe the solution you'd like**
This design needs to be updated to the screenshot below.

https://www.figma.com/file/VGGqwl3Eq3GQIAO9I6LoNW/PHLASK?type=design&node-id=8303-160428&mode=design&t=yxa3UdeM8FBh6T0I-0

**Describe alternatives you've considered**
N/A

**Additional context**
![image](https://github.com/phlask/phlask-map/assets/104399179/804f7b26-72c1-4689-8a14-2b457d36a1ad)

**Comment by lxh5395** [comment]
Looks like "Join the Team" is duplicated on the beta site. There's the title but then a repeat under it. Besides that little thing, looks good!

**Comment by tomporvaz** [comment]
@ilianamiltiadous Thank you for your work on this.  I am closing this issue and reopening a new issue #395 to address the duplicate title raised by the reviewer.  Feel free to grab the new ticket.
