### ISSUE TITLE
Update SelectedTap Modal on Desktop to V2 Design

### ISSUE THREAD

**Issue by tomporvaz** [phlask/phlask-map#366]
**Is your feature request related to a problem? Please describe.**
The SelectedTap modal on desktop should match the new V2 designs. When a user selects resource pin on the map a modal opens on the left side of the screen.

**Describe the solution you'd like**
Make the SelectedTap Modal look like this: 

![Screenshot from 2023-12-28 13-11-09](https://github.com/phlask/phlask-map/assets/45155555/aa2e91da-730a-4ee6-a05f-62c669e78990)
https://www.figma.com/file/VGGqwl3Eq3GQIAO9I6LoNW/PHLASK?type=design&node-id=8303-161391&mode=design&t=vVRkRN4MSA1SQjJY-4

**Describe alternatives you've considered**
n/a

**Additional context**
Previously worked on in issue #305, and requires coordination with assignee of issue #361.  Some changes may overlap, and coordination is likely required to avoid conflicting changes.

**Comment by vontell** [comment]
@tomporvaz because of how I am implementing this in #361, I am happy to just combine these two tickets into #361 as well. The desktop and mobile versions will use the same content components, and all that changes is how it's displayed (which is already implemented by previous work).

**Comment by tomporvaz** [comment]
Got it! I suspected as much, but I was hoping to make two issues of this.  Is there room for two people on this issue?  Let's combine it, and if you think there is room for someone to help, we'll add a help wanted flag to #361.

**Comment by tomporvaz** [comment]
Closing this issue to merge with #361.  #361 one should implement SelectedTap desktop modal from v2 design in addition to mobile SelectedTab modal.

**Comment by vontell** [comment]
@tomporvaz sounds good! Sure thing, happy to take someone else on who wants to assist/learn!

**Comment by vontell** [comment]
Sorry @tomporvaz! Actually re-opening this so we can have a smaller PR for the current changes. I have a PR open now (#387) and will be working on this next, which should _hopefully_ be trivial.

**Comment by tomporvaz** [comment]
@vontell Implemented much of the logic for the Desktop modal when he built the Mobile modal (issue #361).  Take a look around and reach out to Aron if you have questions about the exiting code.

**Comment by vontell** [comment]
I am now taking this on as part of the hackathon
