### ISSUE TITLE
Contact Design update for Desktop

### ISSUE THREAD

**Issue by freelyPheobe** [phlask/phlask-map#367]
**Is your feature request related to a problem? Please describe.**
Not a problem, just design update.

**Describe the solution you'd like**
Remove social media icons from first page of contact form( facebook, instagram, twitter). This should not erase the icons on the "thanks for your feedback!" located on second page of contact form. See screenshot below.

**Describe alternatives you've considered**
N/A

**Additional context**
![image](https://github.com/phlask/phlask-map/assets/104399179/c11a0e8d-5bb5-41ad-b4e2-44e2030ad4e0)

**Design**
Designer: Logan Hebert @loganhebert

**Comment by lxh5395** [comment]
Looks good!! 👍
