### ISSUE TITLE
"Add resources" page for MOBILE

### ISSUE THREAD

**Issue by freelyPheobe** [phlask/phlask-map#369]
**Describe the bug**
Add Resources button has to be deleted from the menu in the top left corner ONLY.

**To Reproduce**
N/A

**Expected behavior**
It shouldn't be there because it should already be in the modal below.

**Screenshots**
![image](https://github.com/phlask/phlask-map/assets/104399179/3b846110-50b8-4cff-bbc6-dab991065e86)

**Desktop (please complete the following information):**
 N/A

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ketansahugit** [comment]
Hi, I'd like to work on this issue but just wanted to confirm before moving forward.....is this a suggestion that needs to be approved by the maintainers or i can start working on it straight away?

**Comment by freelyPheobe** [comment]
@ketansahugit Feel free to take this on! This doesn't have tags such as "clarity," or "blocked," so you're good to go!

**Comment by ketansahugit** [comment]
@freelyPheobe  Hey, I have opened a PR. please check it out.

**Comment by freelyPheobe** [comment]
@ketansahugit Thanks for completing this task @gcardonag or @RNR1 will check it out when they have a chance.

**Comment by gcardonag** [comment]
I have reviewed the PR and merged it, thank you so much for the contribution @ketansahugit ! 🙇
