### ISSUE TITLE
filter does not update map for water cooler or other not implemented types

### ISSUE THREAD

**Issue by tomporvaz** [phlask/phlask-map#370]
**Describe the bug**
When I choose a filter that has no data, nothing changes on the screen.  For example, as demonstrated in the recording below, I choose a water filter of soda machine, but there is no change of which pins are displayed.  This could indicate that all pins rendered are soda machines, but I think this is highly unlikely.  I think it is more likely that soda machines is not an implemented tag, and the null result from this query is affecting no change. 

**To Reproduce**

https://github.com/phlask/phlask-map/assets/45155555/5f019746-2588-42cb-bd48-06651912083e

**Expected behavior**
The map should show no pins or an error message to indicate that there are no results matching that filter.  

**Screenshots**
n/a

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**
Feature implemented in #215 and solution may be related to #344

**Comment by vontell** [comment]
This will be part of my new data schema PR #433

**Comment by tomporvaz** [comment]
@vontell is making a big PR related to the new data schema that will address this issue soon.
