### ISSUE TITLE
Filter type does not change when the Resource Type is changed

### ISSUE THREAD

**Issue by tomporvaz** [phlask/phlask-map#371]
**Describe the bug**
When I change the resource type of the map, for example foraging, the resource type of the filter does not change to a foraging filter.  

**To Reproduce**
Use the resource button to change the resource of the map to foraging, and then then open the filter modal to see which filter is available.

**Expected behavior**
Filter type should match the current resource type of the map.

**Screenshots**

https://github.com/phlask/phlask-map/assets/45155555/36d6de95-ebdb-4d73-94e9-44c159da2355

**Desktop (please complete the following information):**
 n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**
Feature implemented in https://github.com/phlask/phlask-map/issues/215 and solution may be related to https://github.com/phlask/phlask-map/issues/344

**Comment by affabillyty** [comment]
Hey @tomporvaz , it looks like this one has been fixed! 💯  I was checking the beta site and this seems to work now.

Do you know if someone fixed it based on this ticket, or did it as part of other work? Just want to make sure we have it attributed and recorded for acknowledgements purposes

**Comment by affabillyty** [comment]
This one seems to be working on desktop now, however there is a newer bug on mobile where the Resource Menu and Filter buttons are no longer working
