### ISSUE TITLE
About Page for MOBILE

### ISSUE THREAD

**Issue by freelyPheobe** [phlask/phlask-map#372]
**Describe the bug**
Currently nothing happens when the about page is clicked

**To Reproduce**
1. Go to top left menu
2. Click on 'about'
3. Scroll down to 'nothing will happen :('
4. Please update

**Expected behavior**
See screenshot below

**Screenshots**
![image](https://github.com/phlask/phlask-map/assets/104399179/097df911-6ae0-4307-afd5-4c00dd184d2e)

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by tomporvaz** [comment]
Blocked because issue #382 should be complete before implementing this page on mobile.
