### ISSUE TITLE
"Join the team" page on MOBILE

### ISSUE THREAD

**Issue by freelyPheobe** [phlask/phlask-map#373]
**Is your feature request related to a problem? Please describe.**
This feature is not related to a problem but rather an update
**Describe the solution you'd like**
Refer to the screenshot below and make it do what it do!

**Describe alternatives you've considered**
N/A

**Additional context**
![image](https://github.com/phlask/phlask-map/assets/104399179/1aad2881-6450-4b33-8a9f-adfc068f039a)

Additional information from design team:
![image](https://github.com/phlask/phlask-map/assets/104399179/835f588c-99cf-4bf3-8ef8-b43e93244aa6)

**Comment by tomporvaz** [comment]
Blocked because issue #382 should be complete before implementing this page on mobile.
