### ISSUE TITLE
Contact for MOBILE

### ISSUE THREAD

**Issue by freelyPheobe** [phlask/phlask-map#374]
**Is your feature request related to a problem? Please describe.**
Head to the top left corner of the page and add a "Contact" option to the Menu just like the immediate pic below.
![image](https://github.com/phlask/phlask-map/assets/104399179/3d9d3e63-9917-477d-b3bc-582a8822b1f4)

**Describe the solution you'd like**
The information in the image below has to be made into two separate pages.
![image](https://github.com/phlask/phlask-map/assets/104399179/8ee4b9ba-4caa-48f2-a58f-0fd9e4e86ca8)

**Describe alternatives you've considered**
N/A

**Additional context**
This ticket is for Peer Programming during HackNight. No exceptions.

**Comment by tomporvaz** [comment]
Working with Ron tonight, and another senior dev in the future.

**Comment by ilianamiltiadous** [comment]
Cannot be worked on until head.js is implemented for mobile

**Comment by tomporvaz** [comment]
Blocked because issue #382 should be complete before implementing this page on mobile.
