### ISSUE TITLE
Beta site bug

### ISSUE THREAD

**Issue by freelyPheobe** [phlask/phlask-map#376]
**Describe the bug**
There is a "$" that shows up on the lower left corner of screen. Its to the left of the "near me" button.
**To Reproduce**
1. Go to beta site
2. Scroll down to left lower corner( left of the near resources button)
3. Behold the sneaky cash symbol

**Expected behavior**
It just has to be removed from the code.

**Screenshots**
![image](https://github.com/phlask/phlask-map/assets/104399179/8697139b-c30c-47d8-8e84-b9ff225a4df3)

**Desktop (please complete the following information):**
 
**Smartphone (please complete the following information):**
 

**Additional context**
 "Where in the world is Carmen San Diego??" <----This is a bad joke...nice work in spotting the error!

**Comment by ilianamiltiadous** [comment]
Bug no longer exists!
