### ISSUE TITLE
Update V.2 Head and Menu (MOBILE)

### ISSUE THREAD

**Issue by tomporvaz** [phlask/phlask-map#382]
**Is your feature request related to a problem? Please describe.**
As a part of the effort to deploy PHLASK 2.0, we would like the Head and Menu opened by the hamburger button in the src/components/Head folders to match the design in the Mobile design shared here:
https://www.figma.com/file/VGGqwl3Eq3GQIAO9I6LoNW/PHLASK?type=design&node-id=8036-117349&mode=design&t=pgldXk7kfEtath5H-0

![Screenshot from 2024-01-14 21-39-17](https://github.com/phlask/phlask-map/assets/45155555/30b03cff-31a2-4ca2-b236-9db26c7d3ce8)

**Describe the solution you'd like**
Work has already been completed on updating Head and Menu on desktop (#301) and the mobile implementation should follow the same design pattern.  Please reuse components and logic in head.js where possible, and componentize shared views if possible while prioritzing adherence to the figma design. 

**Describe alternatives you've considered**
n/a
**Additional context**
#301

**Comment by tomporvaz** [comment]
@as3445 Are you working on this issue?  Can you share your progress with us?  We are pushing for an end of May release of version 2.0 and this is core functionality that we need for other features.

**Comment by as3445** [comment]
@tomporvaz, it's WIP, i'll push updates by the end of the weekend!
