### ISSUE TITLE
Near Me Button Functionality

### ISSUE THREAD

**Issue by tomporvaz** [phlask/phlask-map#385]
**Is your feature request related to a problem? Please describe.**
The near me button on desktop and mobile should pan the map to the location of the closest resource to your devices location, change that locations pin to the selected pin that has an inverted color scheme and open the SelectedTap modal for that resource, or the half modal if on mobile.  

**Describe the solution you'd like**
Currently is seems as though the main feature that is not implemented yet is the map moving its focus to the closest pin.  

The selected pin does not update to the active pin either, and this feature is not implemented anywhere in the app. The inverted/selected pin is a feature that is being work on in #386 , but once it has, it should be implemented in this context too. 

Likewise, the half-modal has not been implemented anywhere on the map.  It is being worked on in issue #361, but once implemented there, it should also be used when clicking on near me button.

**Describe alternatives you've considered**
n/a

**Additional context**
Previously worked on in issue #216.

~~**Blocker: #361 not yet complete**~~

**Comment by affabillyty** [comment]
Hey @tomporvaz , I see this one is in the backlog column. Knowing that it's a core feature, I was wondering if there's anything else that is blocking it from moving it to the Ready column.

**Comment by tomporvaz** [comment]
@gcardonag mentioned that the actual 'logic' and math for the feature is built, but just needs to be inserted into v2.0.

**Comment by tomporvaz** [comment]
Hi @astoppop,

I hope you're doing well. I wanted to check in on the status of this issue. Could you please provide an update on the current progress?

Thank you for your time and effort on this project.

**Comment by vontell** [comment]
@tomporvaz I believe this is also fixed by my PR, so I'm happy to take this on.

**Comment by vontell** [comment]
Update on this ticket - the near me button works, but it goes to any nearest resource, rather than the nearest resource based on the filters currently applied (for instance, if you are viewing Food, it may bring you to the nearest Water resource). This should be a simpler ticket now, making sure to use the filtered resources rather than allResources for the nearest feature.
