### ISSUE TITLE
[V2] Update form submission for new data format

### ISSUE THREAD

**Issue by vontell** [phlask/phlask-map#391]
**Is your feature request related to a problem? Please describe.**
With the new [data format](https://docs.google.com/document/d/1ES2_ZrWGLYzAMOkri9nHrcAsvj5yHz979Y9HKwcFfuY/edit) defined, the submission forms need to be updated to match the new schema. For instance, the address is now optional, where the address was required before.

The first part of this task is to define the new schema as a class, just so we can have some structure. Then, the existing fields in the form need to be updated to match this new type. More specifically, the code at [AddResourceModalV2.jsx - line 231](https://github.com/phlask/phlask-map/blob/develop/src/components/AddResourceModal/AddResourceModalV2.jsx#L231-L302) is where we take the information from the add resource forms, and then submit it to our firebase DB.

Please talk to @vontell for more context. Note that this does not cover adding new information like lat/lon coordinates - that will be covered in other tickets.

**Comment by tomporvaz** [comment]
Big PR will address this issue soon.

**Comment by vontell** [comment]
This is now complete

**Comment by tomporvaz** [comment]
@vontell Does PR #391 address this issue?
