### ISSUE TITLE
[V2] Populate lat/lng properly before form submission

### ISSUE THREAD

**Issue by vontell** [phlask/phlask-map#392]
This task is all about adding **latitude and longitude** information to the resource submission page.

First, take a look at [AddResourceModalV2.jsx - line 231](https://github.com/phlask/phlask-map/blob/develop/src/components/AddResourceModal/AddResourceModalV2.jsx#L231-L302). You'll see here that we take the information from the add resource forms, and then submit it to our firebase DB.

You'll also notice, however, that the latitude and longitude is not included here. Our goal for this task is to add the user's latitude and longitude for that location.

Inside of the [AddResourceModalV2.jsx](https://github.com/phlask/phlask-map/blob/develop/src/components/AddResourceModal/AddResourceModalV2.jsx), we can access the user's location using:

```
const userLocation = useSelector(state => state.userLocation);
```

You can search for other instances of `userLocation` in the code to see what its format looks like. What you can do is then add a `latitude` and `longitude` field to the JSON being submitted in that on submit button.

This is the first step in our task of supporting the addition of this information - in another follow up issue and PR, we will also need to make sure that the user has location enabled.

To verify your work, you should console.log the JSON before it gets sent to firebase, and you should be able to view the networking profiler in chrome and see if a request was sent with the lat/long.

I am happy to hop into a call and help debug and review! I assume that will be needed since this will be your first task.

**Comment by freelyPheobe** [comment]
Currently going through testing.

**Comment by freelyPheobe** [comment]
-Only allowed to ask user location once.
- Addresses can be associated with Parks and the like.  Thus utilizing a precise lat/long gives a more accurate position.
-Also- we have to plan for users that add locations other than their current location (ex. water fountains in a mall).

-Version 2. XX coming to a Phlask near you.

**Comment by tomporvaz** [comment]
@vontell and @Tom-from-6520 I wondering how this ticket it going.  Please comment an update on the status of this ticket.  Is Tom still working on this?

**Comment by vkavith** [comment]
I will take this ticket

**Comment by vkavith** [comment]
Is Tom-from-6520 already working on this ?

**Comment by tomporvaz** [comment]
@vkavith Lets see if we get a response from @Tom-from-6520 or @vontell by next Tuesday 4/23. Vontell could probably give us an update at the meeting.

**Comment by Tom-from-6520** [comment]
Hi, I apologize for holding on to this ticket. I'm not working on it currently.

**Comment by vontell** [comment]
@vkavith if you want to take this on, that would be great! It would be best to do this one before the other tickets, as it is probably the easiest out of the other tickets and is a good intro.
