### ISSUE TITLE
Update Water Filter Add "vessel" Remove "water jug" and "pitcher"

### ISSUE THREAD

**Issue by tomporvaz** [phlask/phlask-map#409]
**Is your feature request related to a problem? Please describe.**
A recent design update has changed the dispenser types for Water.  Dispenser type "pitcher" and "water jug" are being condensed to "vessel", as such, the water filter needs to reflect this change by removing the "pitcher" and "water jug" types, and adding the "vessel" type. 

**Describe the solution you'd like**
https://www.figma.com/file/VGGqwl3Eq3GQIAO9I6LoNW/PHLASK?type=design&node-id=8036-111315&mode=design&t=sIaTQXTFkp2mkx2a-0
![water_filter_vessel_type](https://github.com/phlask/phlask-map/assets/45155555/ed1deebf-41d7-4d63-aaa8-5d058c63e724)

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by vkavith** [comment]
I will check this ticket today
