### ISSUE TITLE
Remove Info Icon from Desktop

### ISSUE THREAD

**Issue by tomporvaz** [phlask/phlask-map#411]
**Describe the bug**
An information icon appears in the bottom left corner of map on desktop.  Clicking on icon opens the tutorial modal.  This should not be there and should be removed. See screenshot below.

**To Reproduce**
open map on desktop

**Expected behavior**
n/a

**Screenshots**
![image](https://github.com/phlask/phlask-map/assets/45155555/aed5c53a-315f-4933-bbd2-6c6abc03d948)

**Desktop (please complete the following information):**
Windows 10

**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by JosephAni** [comment]
Fixed!
<img width="303" alt="bug" src="https://github.com/phlask/phlask-map/assets/63737588/92a6fd36-b6c5-4bf1-b180-7d33b2acf286">
