### ISSUE TITLE
[V2] Cleanup old Add Resource and Display Resource code

### ISSUE THREAD

**Issue by vontell** [phlask/phlask-map#414]
**Is your feature request related to a problem? Please describe.**
Now that we are updating the code that uploads and pulls the resources, we have identified a few potential places where V1 code is no longer used, and is confusing to update. This ticket is to remove a few older parts of the Add Resource code and code related to pulling and displaying resoueces that is no longer used. This will help us with our next ticket, #415 

**Describe the solution you'd like**
Remove old code that is no longer used related to adding resources and displaying resources. For instance, the `AddTapModal`. You can also search for `@deprecated` for a few components that @Erw1nn marked as deprecated.

**Comment by vontell** [comment]
@Erw1nn I made this ticket last week, and just realized you went and marked some of these as deprecated recently. Just wanted to confirm if this ticket is ok with you, I was thinking of having someone remove these fairly soon since it will help new folks understand the codebase a little better.

**Comment by Erw1nn** [comment]
> @Erw1nn I made this ticket last week, and just realized you went and marked some of these as deprecated recently. Just wanted to confirm if this ticket is ok with you, I was thinking of having someone remove these fairly soon since it will help new folks understand the codebase a little better.

Yeah that's totally fine!

**Comment by vontell** [comment]
This is now complete as well.
