### ISSUE TITLE
Give forms the ability to set either the address location or current location

### ISSUE THREAD

**Issue by vontell** [phlask/phlask-map#426]
**Is your feature request related to a problem? Please describe.**

In a previous ticket (#392), we added the existing latitude and longitude for a resource into the Firebase data. However, we so far only implemented the option of "use my existing address", not the address of an address typed in. This ticket is to make sure that the user has both options.

**Describe the solution you'd like**

The logic should be as follows:
- If the user provides an address (by searching or typing), we should use that latitude and longitude from the google places API.
- If they don't type out an address and click the "use my location" button, it should use that exact lat and long, **and** also populate the new address at that location into the Street address field.

**Comment by kdmonroe** [comment]
I can take this!

**Comment by tomporvaz** [comment]
Nearly completed, but looking for ability to test data up take on backend.
