### ISSUE TITLE
Update Contributor Herbert to Hebert

### ISSUE THREAD

**Issue by tomporvaz** [phlask/phlask-map#456]
**Describe the bug**
There is a typo in the spelling of Logan Hebert in the Phlask contributor database.  Its currently spelled as Logan Herbert and should be updated to Logan Hebert.

**To Reproduce**
Open Join the Team from the Hamburger menu in top left.  Scroll down to Acknowledgments section.

**Expected behavior**
Update to Hebert

**Screenshots**
![hebert_contributor](https://github.com/phlask/phlask-map/assets/45155555/6b4567b0-0626-48f0-ad08-f1f4f46fd782)

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**
Will need firebase access to update.

**Comment by vontell** [comment]
This has now been fixed - marking as closed.
