### ISSUE TITLE
Catch errors when converting address to lat/lng

### ISSUE THREAD

**Issue by vontell** [phlask/phlask-map#460]
In some cases, attempting to create a new resource results in an error message. Sometimes this is related to a failure in geocoding the address (i.e. trying to get the lat/lng for an address), but in some other cases, another error happens. We should capture any error when submitting a resource and display a message in the dialog, rather than crashing the app.

**Comment by gcardonag** [comment]
@vontell , I know we shared this during today's standup, but I'll look for your help to confirm whether this is still active while I review other tickets tonight. 🙏
