### ISSUE TITLE
Randomize the list order of contributors

### ISSUE THREAD

**Issue by vontell** [phlask/phlask-map#461]
The Contributors list (click the menu and click on "Join the Team") is currently hardcoded to a certain order. We would like to randomize the order in which these items are displayed, so that no one team member is listed in a certain spot.

<img width="1669" alt="Screenshot 2024-06-23 at 3 14 48 PM" src="https://github.com/phlask/phlask-map/assets/8053203/a4d4c8dc-c9c7-4886-8cfd-ab2a9edbfee5">

**Comment by gcardonag** [comment]
@IanFalkinburg , closing this one with the linked PR we merged from @TineoC . That said, feel free to review this if you'd like to contribute any feedback to improve what was implemented.
