### ISSUE TITLE
PHLASK Map Filtering

### ISSUE THREAD

**Issue by affabillyty** [phlask/phlask-map#51]
As a user, the map needs to have a filtering panel so that we can filter by tap type.

Users should be able to filter by:
- ADA Accessibility
- Tap Type
- Filtered / Unfilted water

[Map Mobile - mockups.pdf](https://github.com/phlask/phlask-map/files/3598144/Map.Mobile.-.mockups.pdf)

**Comment by krishna-dasika** [comment]
please assign me to this task

**Comment by krishna-dasika** [comment]
the mockups are showing mobile mockups do we have the same filters in web too?
