### ISSUE TITLE
Add Resource Modal on Mobile Design Update

### ISSUE THREAD

**Issue by tomporvaz** [phlask/phlask-map#519]
**Is your feature request related to a problem? Please describe.**
Add Resource modal on mobile design does not match figma design.  Currently, the modal looks like this:
![image](https://github.com/user-attachments/assets/689769a4-80db-4d49-aef2-4bf963a2e64e)

**Describe the solution you'd like**
After clicking the Add Site button on mobile, a modal should open that looks like this: 
![image](https://github.com/user-attachments/assets/96ce0606-165e-4a32-aac5-30819af9ebbb)

You can view the [Figma file for this section](https://www.figma.com/design/VGGqwl3Eq3GQIAO9I6LoNW/PHLASK?node-id=8036-118966&t=SDSTpwGsDFlj9SRa-0) for precise proportions.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Designer** 
Logan @lxh5395

**Comment by gcardonag** [comment]
This was already completed by @astoppop as a part of https://github.com/phlask/phlask-map/pull/516

Closing this ticket and assigning it for design review

**Comment by lxh5395** [comment]
Looking good. 

One small request, could we remove the line bread after "like"? On certain resolutions it ends up separating the text weird.
![image](https://github.com/user-attachments/assets/d545793a-e948-4b9c-9faa-cf8eebfb9ecf)
