### ISSUE TITLE
Map Not Loading - Bug

### ISSUE THREAD

**Issue by affabillyty** [phlask/phlask-map#58]
As a user, the map is not loading for me on Google Chrome.

There is an 'error' icon for location services in the URL with a message that says:

----

The following sites have been blocked from tracking your location on this page: beta.phlask.gcardona.me

Settings will be cleared on the next reload

----

Even if the user does not share their location, or the browser cannot access the location, it would be good to have a contingency that can still load the map and center it on City Hall

**Comment by gcardonag** [comment]
hey @affabillyty , if you get this message again, could you take a screenshot and share it? I've never seen that happen before but I wonder if that's something Google is doing in Chrome before our page even loads as a security measure.
