### ISSUE TITLE
Non-Phlask taps are showing tooltips

### ISSUE THREAD

**Issue by waltribeiro** [phlask/phlask-map#78]
**Bug Description**
A tooltip appears on all searched locations

**Steps To Reproduce**
1.) Go to beta.phlask.me
2.) Searching a specific address
3.) Notice how Google Maps lands a pin on that exact location
4.) Click on that Google Maps pin icon
5.) Notice how it creates a pop-up tooltip

**Expected behavior**
Since the address is not a Phlask icon, then the tooltip should not appear

**Screenshots**
Attached

**Desktop Setup**
 - OS: [macOS 10.15.2]
 - Browser [Google Chrome version 79.0.3945.130]

**Mobile Setup**
 - Device: [iPhone 11 Pro]
 - OS: [iOS 13.3]
 - Browser [Safari]
![tap-tooltip-bug](https://user-images.githubusercontent.com/5629979/74848313-8c2e2e00-5305-11ea-8a7c-6c4fd63d6185.jpg)

**Comment by gcardonag** [comment]
@waltribeiro - Could you test this again on the beta site(https://beta.phlask.me)? I believe we may have fixed this when moving to the new info panels.

**Comment by gcardonag** [comment]
Closing as this has been resolved ✅
